name: Deploy and Publish (Development)

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-dev"
  cancel-in-progress: false

jobs:
  deploy-and-publish-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Create dev version and publish to NPM
        run: |
          # Create dev version (e.g., 1.0.0-dev.1)
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          DEV_VERSION="${CURRENT_VERSION}-dev.$(date +%s)"
          npm version $DEV_VERSION --no-git-tag-version
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_ENV
          git add package.json
          git commit -m "chore: bump dev version to $DEV_VERSION"
          git push origin dev
          
          # Publish to NPM with dev tag
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

      - name: Deploy to GitHub Pages (Dev)
        id: deployment
        uses: actions/deploy-pages@v4
